spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    virtual-host: /
  redis:
    host:
      localhost
    port: 6379
    database: 0
    password: tttx
server:
  port: 8080